name: the_good_friend_medallion
description: A Flutter app for peer-to-peer friend tracking using BLE and GPS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # BLE 扫描与连接
  flutter_blue_plus: ^1.31.7

  # 获取 GPS 位置
  geolocator: ^10.0.1

  # 控制震动反馈
  vibration: ^3.1.3


  # 权限管理
  permission_handler: ^11.0.1

  # 可选：UI 图标风格
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

