name: the_good_friend_medallion

description: A Flutter app that scans for BLE and gives feedback based on proximity using system HapticFeedback.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.7
  geolocator: ^10.0.1
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true